# Default log level for all packages
org.slf4j.simpleLogger.defaultLogLevel=info

# Suppress AWS SDK debug logs
org.slf4j.simpleLogger.log.software.amazon.awssdk=WARN

# Show your app logs normally
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=true
